input_vcf: 'cohort.smoove.square.anno.DHFFC0.7.vcf.gz'
aaf_change: '0.2'
family_name: ''
ped: 'cohort.ped'
pick: 'canonical'
samtools_version: 'samtools/1.6'
ref_genome: '/data/OGVFB/resources/human_g1k_v37_decoy.fasta'
VEP_version: 'VEP/94'
vcfanno_version: 'vcfanno/0.2.9'
vcfanno_lua: '/home/mcgaugheyd/git/variant_prioritization/src/vcfanno_custom.lua'
vcfanno_conf: '/home/mcgaugheyd/git/variant_prioritization/src/vcfanno_SV_v001.conf'
vcf2db_version: 'vcf2db/2017.12.11'
gemini_version: 'gemini/0.20.1'
peddy_version: 'peddy/0.3.1'
R_version: 'R/3.5'
pandoc_version: 'pandoc/2.1.1'
gemini_lenient: 'Yes'
SeeGEM_script: '/home/$USER/git/variant_prioritization/src/GEMINI_db_to_SeeGEM.R'
regions: '/home/mcgaugheyd/git/variant_prioritization/src/vcf_region_split_100_coords.txt'
