input_vcf: 'VCFs.GATK.vcf.gz'
aaf_change: '0.9'
family_name: ''
ped: 'COHORT.ped'
pick: 'canonical'
samtools_version: 'samtools/1.6'
ref_genome: '/data/OGVFB/resources/mcgaughey_annotation_files/human_g1k_v37_decoy.fasta'
VEP_version: 'VEP/92'
vcfanno_version: 'vcfanno/0.2.9'
vcfanno_lua: '~/git/variant_prioritization/src/vcfanno_custom.lua'
vcfanno_conf: '~/git/variant_prioritization/src/vcfanno_v2.conf'
vcf2db_version: 'vcf2db/2017.12.11'
gemini_version: 'gemini/0.20.1'
peddy_version: 'peddy/0.3.1'
python2_version: 'python/2.7'
R_version: 'R/3.5'
annovar_version: 'annovar/2018-04-16'
InterVar_version: 'InterVar/2.0.1'
intervar_Rscript_path: '~/git/variant_prioritization/src/intervar_v1.5.R'
pandoc_version: 'pandoc/2.1.1'
gemini_lenient: 'Yes'
SeeGEM_script: '~/git/variant_prioritization/src/GEMINI_db_to_SeeGEM.R'
regions: '~/git/variant_prioritization/src/vcf_region_split_2_coords.txt'
