input_vcf: 'VCFs.GATK.vcf.gz'
aaf_change: '0.1'
family_name: ['COL036','COL076','COL091','COL114','COL130','COL158','COL159','DDL012','DDL013','DDL014','DDL015','DDL016','DDL017','DDL018','DDL019','DDL019','DDL020','DDL021','dor_yeshorim','dor_yeshorim','ambry','W89','W90','W97','W100','W107','W103','ZEIN_15-29-31','CCGO_FAM_800532','CCGO_FAM_800594','CCGO_FAM_800643','CCGO_FAM_800666','CCGO_FAM_800778','CCGO_FAM_800016and18','CCGO_FAM_800016and18','CCGO_FAM_800044','CCGO_FAM_800062','CCGO_FAM_800067and71','CCGO_FAM_800067and71','CCGO_FAM_800118','CCGO_FAM_800157','CCGO_FAM_800160','CCGO_FAM_800160','CCGO_FAM_800188','CCGO_FAM_800298','CCGO_FAM_800308','CCGO_FAM_800347','CCGO_FAM_800412','CCGO_FAM_800513','CCGO_FAM_800520','CCGO_FAM_800524','W23','DDL001','DDL002','DDL003','DDL004','DDL004','DDL004','DDL005','DDL005','DDL006','DDL007','DDL008','DDL009','DDL010','DDL011','DDL012','fam5','fam5','fam5','fam34','fam34']
ped: '/home/mcgaugheyd/git/NGS_db/master.ped'
pick: 'canonical'
gemini_db_name: 'gemini_db/MVL_2017-12-14.gemini.db'
samtools_version: 'samtools/1.6'
ref_genome: '/data/OGVFB/resources/human_g1k_v37_decoy.fasta'
VEP_version: 'VEP/92'
vcfanno_version: 'vcfanno/0.2.9'
vcfanno_lua: '/home/$USER/git/casey_to_gemini/src/vcfanno_custom.lua'
vcfanno_conf: '/home/$USER/git/casey_to_gemini/src/vcfanno_exomes.conf'
vcf2db_version: 'vcf2db/2017.12.11'
gemini_version: 'gemini/0.20.1'
peddy_version: 'peddy/0.3.1'
R_version: 'R/3.5'
pandoc_version: 'pandoc/2.1.1'
gemini_lenient: 'Yes'
SeeGEM_script: '/home/$USER/git/variant_prioritization/src/GEMINI_db_to_SeeGEM.R'
regions: '/home/mcgaugheyd/git/variant_prioritization/src/vcf_region_split_100_coords.txt'
